### ISSUE TITLE
Circular JSON error crashes dev tools

### ISSUE THREAD

**Issue by tony-g** [tannerlinsley/react-query-devtools#20]
Hi!  Getting a crash in v1.1.5.

The minimum repro seems to be:
(1)
```js
  return useQuery(['a'], async () => {
    const a = { a: undefined }
    a.a = a
    return a
  })
```

(2) Click that query to inspect in devtools
![image](https://user-images.githubusercontent.com/834042/80019058-cba30300-848b-11ea-8b55-ebfe42a0093e.png)

Devtools crashes

![image](https://user-images.githubusercontent.com/834042/80018500-f2ad0500-848a-11ea-8c3d-fa707854c2a2.png)

As a little more context, I came across this crash when I was using react-query to load a pdf into pdf-lib's PDFDocument, and then returning that document.  I don't actually have any need to inspect the contents of that object in devtools, just wanted access to the other query info.

Thanks for the amazing library!

**Comment by tannerlinsley** [comment]
Yeah... we'll have to find a way around this. Darn circular references... ;)

**Comment by jackmellis** [comment]
I actually seem to get this error from it trying to serialise the query itself. I've definitely don't have any recursive data in my request/response

```
    --> starting at object with constructor 'Object'
    |     property 'cache' -> object with constructor 'Object'
    |     property 'queries' -> object with constructor 'Object'
    --- property '["@@ux/accounts-client/ACCOUNT","my"]' closes the circle
```
I don't know if something's changed recently to make this problem even worse?

**Comment by justinramel** [comment]
I'm seeing this error too, don't think its my query but rather this line:

https://github.com/tannerlinsley/react-query-devtools/blob/d2b880fa96daa85565bf85576e59bf5c2e126e7a/src/index.js#L210

The activeQuery object has a `cache` property that references itself, causing the circular reference exception.

I fixed it locally by deleting the `cache` property before the `JSON.stringify`.

```
      if (activeQuery) delete activeQuery.cache;
      return [activeQuery, activeQuery ? JSON.parse(JSON.stringify(activeQuery)) : null];
```

Happy to send a pull request but not sure what problems deleting the `cache` will have! 

It does however work on my machine™️

**Comment by jackmellis** [comment]
Rather than deleting the active query from your actual code, you could use the `replacer` function of JSON.stringify to just exclude it during stringification...

**Comment by justinramel** [comment]
Good Idea @jackmellis, mine was just a quick bodge to get it working 😄

**Comment by Frumba** [comment]
Hello ! I also have the same issue from recently when using useInfiniteQuery and i don't have any circular dependencies in the data i get from the API.

Here is the error:
`--> starting at object with constructor 'Object'
    |     property 'queries' -> object with constructor 'Object'
    |     property '["products",{"predicates":[{"attribute":"recipe","comparison":"equals","type":"boolean","value":false}],"sortBy":"name","sortDirection":"ASC"}]' -> object with constructor 'Object'
    --- property 'cache' closes the circle`

Am i missing something when configuring my call?

Thanks a lot for your hard work !

**Comment by pinkeyAT** [comment]
We have the same issue and wondering if its something in react-query itself? 
With react-query 1.4.4 its working with and with react-query >= 1.5.0 its broken and we get even for the simplest query this error

**Comment by omarkhatibgg** [comment]
Hi @tannerlinsley 

I just got the same error.

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'cache' -> object with constructor 'Object'
    |     property 'queries' -> object with constructor 'Object'
    --- property '["locations"]' closes the circle
```

**Comment by therealravitej** [comment]
same issue.

**Comment by elrypto** [comment]
Have it as well (data structure is flat)

**Comment by FrimJo** [comment]
@tannerlinsley I've created a PR #27 with @jackmellis proposal of using replace callback of `JSON.stringify()`.

**Comment by sudokoi** [comment]
@tannerlinsley  npm package hasn't been updated yet.
![image](https://user-images.githubusercontent.com/22864071/83124367-c02ea180-a0f3-11ea-8467-cacb61f338a7.png)

**Comment by larryyangsen** [comment]
I got the same error with react-query@2.5.8 and react-query-devtools@2.4.1

**Comment by uniquedevs** [comment]
> I got the same error with react-query@2.5.8 and react-query-devtools@2.4.1
seems like it is fixed in 2.4.2! Cool.

**Comment by patik** [comment]
I still get the error with react-query@2.5.14 and react-query-devtools@2.4.2
