### ISSUE TITLE
Warning: Cannot update a component (`ForwardRef(ReactQueryDevtoolsPanel)`) while rendering a different component

### ISSUE THREAD

**Issue by Alexandredc** [tannerlinsley/react-query-devtools#45]
When using `queryCache.setQueryData` in a component that is using `useQuery`, React throw this warning 
```
Warning: Cannot update a component (`ForwardRef(ReactQueryDevtoolsPanel)`) while rendering a different component (`Todos`). To locate the bad setState() call inside `Todos`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Todos (at src/index.js:144)
    in div (at src/index.js:143)
    in div (at src/index.js:134)
    in App (at src/index.js:121)
    in ReactQueryConfigProvider (at src/index.js:57)
    in Root (at src/index.js:432)
```

Example :
https://codesandbox.io/s/epic-diffie-swiyq?file=/src/index.js:4415-4466

**Comment by tannerlinsley** [comment]
This is now fixed with the latest versions of both react-query and react-query-devtools

**Comment by Alexandredc** [comment]
Thanks you ! 🎉

**Comment by martinadamec** [comment]
I'm still facing to this issue: 
```
"react-query": "2.12.1",
"react-query-devtools": "2.4.4",
```
simplify code:
```
<ReactQueryConfigProvider config={{}}>
	<Suspense fallback={<LoadingLayout />}>
		<ThroughProvider>
			<AuthContext.Provider value={authContext}>
				<Homepage>
					...
					<Test />
					...
				</Homepage>
			</AuthContext.Provider>
		</ThroughProvider>
		{process.env.NODE_ENV === 'development' && <ReactQueryDevtools initialIsOpen />}
	</Suspense>
</ReactQueryConfigProvider>
```
error message:
```
Warning: Cannot update a component (`ForwardRef(ReactQueryDevtoolsPanel)`) while rendering a different component (`Test`). To locate the bad setState() call inside `Test`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Test (at Homepage.tsx:94)
    in div (at DefaultContainer.tsx:8)
    in DefaultContainer (at Homepage.tsx:84)
    in Homepage (at App.tsx:104)
    in ThroughProvider (at App.tsx:102)
    in App (at src/index.tsx:25)
    in Suspense (at src/index.tsx:24)
    in ReactQueryConfigProvider (at src/index.tsx:23)

  | console.<computed> | @ | index.js:1
  | overrideMethod | @ | react_devtools_backend.js:2273
  | printWarning | @ | react-dom.development.js:88
  | error | @ | react-dom.development.js:60
  | warnAboutRenderPhaseUpdatesInDEV | @ | react-dom.development.js:23241
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21165
  | dispatchAction | @ | react-dom.development.js:15660
  | (anonymous) | @ | index.js:322
  | (anonymous) | @ | queryCache.ts:93
  | notifyGlobalListeners | @ | queryCache.ts:93
  | buildQuery | @ | queryCache.ts:236
  | updateQuery | @ | queryObserver.ts:208
  | QueryObserver | @ | queryObserver.ts:34
  | useBaseQuery | @ | useBaseQuery.ts:19
  | usePaginatedQuery | @ | usePaginatedQuery.ts:60
  | useApiPaginatedQuery | @ | licenses.tsx:26
  | useApiLicenses | @ | licenses.tsx:40
  | Test | @ | Homepage.tsx:23
```

please, do you have any idea, what I do wrong?
